name: Course Task
description: Assignment/admin task
title: "[TASK] Short title"
labels: ["course-task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Task Description
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Expected Evidence / Deliverable
    validations:
      required: true