name: Other PBI
description: Technical or non-user-story backlog item
title: "[PBI] Short title"
labels: ["pbi"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: PBI Type
      options:
        - Technical
        - Design
        - Documentation
        - Testing
    validations:
      required: true

  - type: input
    id: story_points
    attributes:
      label: Story Points
    validations:
      required: false

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
    validations:
      required: false